Document: naviserver
Title: Debian naviserver Manual
Author: <insert document author here>
Abstract: This manual describes what naviserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/naviserver/naviserver.sgml.gz

Format: postscript
Files: /usr/share/doc/naviserver/naviserver.ps.gz

Format: text
Files: /usr/share/doc/naviserver/naviserver.text.gz

Format: HTML
Index: /usr/share/doc/naviserver/html/index.html
Files: /usr/share/doc/naviserver/html/*.html
